---
# tasks file for harden_devices
- name: "Win CIS | Section 2.3.4.1 | Ensure 'Devices: Allowed to format and eject removable media' is set to 'Administrators'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: allocateDASD
    data: 0
    type: string

- name: "Win CIS | Section 2.3.4.2 | Ensure 'Devices: Prevent users from installing printer drivers' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Print\Providers\LanMan Print Services\Servers
    name: "AddPrinterDrivers"
    data: "1"
    type: dword
