#- name: show vars
#  debug:
#    var: hostvars[inventory_hostname]#

- name: check/init swarm
  docker_swarm:
    state: present
    advertise_addr: eth0:2377
  register: __output_swarm
  when: inventory_hostname in groups['_manager'][0]

- name: install manager
  docker_swarm:
    state: join
    timeout: 60
    advertise_addr: eth0:2377
    join_token: "{{ hostvars[groups['_manager'][0]]['__output_swarm']['swarm_facts']['JoinTokens']['Manager']}}"
    remote_addrs: "{{ groups['_manager'][0] }}"
  when: inventory_hostname in groups['_manager'] and inventory_hostname not in groups['_manager'][0]

- name: install worker
  docker_swarm:
    state: join
    timeout: 60
    advertise_addr: eth0:2377
    join_token: "{{ hostvars[groups['_manager'][0]]['__output_swarm']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: "{{ groups['_manager'][0] }}"
  when: 
    - inventory_hostname in groups['_worker']
