---
#  winrm quickconfig ; Enable-WSManCredSSP -force -role Server
- hosts: all
  vars_files:
    - var_groups/win-variables-http.yml
  roles:

    - role: azure-devops-agent
      name: Configure Queue
      vars:
        - az_devops_accesstoken: 
        - az_devops_agent_version: 2.181.1
        - az_devops_agent_user: "az_devops_agent"
        - az_devops_agent_name: "{{ ansible_hostname }}"
        - az_devops_server_url: "https://dev.azure.com/{{ az_devops_accountname }}/"
        - az_devops_agent_folder: "{{ az_devops_default_agent_folder }}"
        - az_devops_work_folder: "{{ az_devops_default_work_folder }}"
        - az_devops_agent_group: "{{ az_devops_default_agent_group }}"
        - az_devops_agent_pool_name: "Default"
        - az_devops_agent_role: "build"
        - az_devops_agent_replace_existing: true
        - az_devops_reconfigure_agent: true

    - role: azure-devops-agent
      name: Configure Deployment Group
      vars:
        - az_devops_accesstoken: 
        - az_devops_agent_version: 2.181.1
        - az_devops_agent_user: "az_devops_agent"
        - az_devops_agent_name: "{{ ansible_hostname }}"
        - az_devops_server_url: "https://dev.azure.com/{{ az_devops_accountname }}/"
        - az_devops_agent_folder: "{{ az_devops_default_agent_folder }}"
        - az_devops_work_folder: "{{ az_devops_default_work_folder }}"
        - az_devops_agent_group: "{{ az_devops_default_agent_group }}"
        - az_devops_agent_pool_name: "Default"
        - az_devops_agent_role: "build"
        - az_devops_agent_replace_existing: true
        - az_devops_reconfigure_agent: true
        - az_devops_project_name: null
        - az_devops_environment_name: null
        - az_devops_environment_tags: null
        - az_devops_deployment_group_name: null
        - az_devops_deployment_group_tags: null