---
- hosts: all
  vars_files:
    - var_groups/win-variables.yml
  roles:

    - role: win-iis
      name: Install IIS

#  tasks:
#    
#    - include_tasks: playbooks/win-coreweb.yml
#      name: IIS LINT