---
# tasks file for harden_passwords

- name: "Win CIS | Section 1.1.1 | Ensure Enforce password history is set to 24 or more passwords"
  win_security_policy: 
    section: System Access
    key: PasswordHistorySize
    value: "{{ passwordhistorysize }}"

- name: "Win CIS | Section 1.1.2 | Ensure 'Maximum password age' is set to '60 or fewer days, but not 0'"
  win_security_policy:
    section: System Access
    key: MaximumPasswordAge 
    value: "{{ maxpasswordage }}"

- name: "Win CIS | Section 1.1.3 | Ensure 'Minimum password age' is set to '1 or more day(s)'"
  win_security_policy:
    section: System Access
    key: MinimumPasswordAge 
    value: "{{ minpasswordage }}"

- name: "Win CIS | Section 1.1.4 | Ensure 'Minimum password length' is set to '14 or more character(s)'"
  win_security_policy:
    section: System Access
    key: MinimumPasswordLength  
    value: "{{ minpasswordlength }}"

- name: "Win CIS | Section 1.1.5 | Ensure 'Password must meet complexity requirements' is set to 'Enabled'"
  win_security_policy:
    section: System Access
    key: PasswordComplexity  
    value: "{{ passwordcomplexity }}"

- name: "Win CIS | Section 1.1.6 | Ensure 'Store passwords using reversible encryption' is set to 'Disabled'"
  win_security_policy:
    section: System Access
    key: ClearTextPassword  
    value: "{{ cleartextpassword }}"

- name: "Win CIS | Section 1.2.1 | Ensure 'Account lockout threshold' is set to '10 or fewer invalid logon attempt(s), but not 0'"
  win_security_policy:
    section: System Access
    key: LockoutBadCount
    value: "{{ lockoutbadcount }}"

- name: "Win CIS | Section 1.2.2 | Ensure 'Reset account lockout counter after' is set to '15 or more minute(s)'"
  win_security_policy:
    section: System Access
    key: ResetLockoutCount
    value: "{{ resetlockoutcount }}"

