---

- name: ensure iis is installed
  win_feature:
    name: 'Web-Server'
    include_sub_features: yes
    include_management_tools: yes
    restart: yes
  notify: remove defaults

- name: ensure path for site exists
  win_file:
    path: '{{iis_site_path|mandatory}}'
    state: directory
  when: iis_site_name|default("",true)

- name: allow iis group access to site path
  win_acl:
    path: '{{iis_acl_path}}'
    user: '{{iis_acl_user|default(omit,true)}}'
    rights: '{{iis_acl_rights|default(omit,true)}}'
    type: '{{iis_acl_type|default(omit,true)}}'
    state: '{{iis_acl_state|default(omit,true)}}'
    inherit: '{{iis_acl_inherit|default(omit,true)}}'
    propagation: '{{iis_acl_propagation|default(omit,true)}}'
  when: iis_site_name|default("",true) and iis_acl_path|default("",true)
