---

- name: restart iis
  win_service:
    name: w3svc
    state: restarted

- name: Remove Defaults - Default Web Site
  win_iis_website:
    name: "Default Web Site"
    state: absent
  listen: remove defaults

- name: Remove Defaults - DefaultAppPool
  win_iis_webapppool:
    name: "DefaultAppPool"
    state: absent
  listen: remove defaults

- name: Remove Defaults - .NET v2.0
  win_iis_webapppool:
    name: ".NET v2.0"
    state: absent
  listen: remove defaults

- name: Remove Defaults - .NET v2.0 Classic
  win_iis_webapppool:
    name: ".NET v2.0 Classic"
    state: absent
  listen: remove defaults

- name: Remove Defaults - .NET v4.5
  win_iis_webapppool:
    name: ".NET v4.5"
    state: absent
  listen: remove defaults

- name: Remove Defaults - .NET v4.5 Classic
  win_iis_webapppool:
    name: ".NET v4.5 Classic"
    state: absent
  listen: remove defaults

- name: Remove Defaults - Classic .NET AppPool
  win_iis_webapppool:
    name: "Classic .NET AppPool"
    state: absent
  listen: remove defaults

