---

- name: restart iis
  win_service:
    name: w3svc
    state: restarted

# install IIS features

- name: Install IIS (Core Web-Server & tools) 
  win_feature:
    name: Web-WebServer, Web-Common-Http, Web-Default-Doc, Web-Http-Errors, Web-Static-Content, Web-Http-Redirect
    state: present
  listen: install features

- name: Web health tools
  win_feature:
    name: Web-Health, Web-Http-Logging, Web-Custom-Logging, Web-Log-Libraries, Web-ODBC-Logging, Web-Request-Monitor, Web-http-Tracing
    state: present
  listen: install features

- name: Web performance tools
  win_feature:
    name: Web-Performance, Web-Stat-Compression
    state: present
  listen: install features

- name: Web security tools
  win_feature:
    name: Web-Security, Web-Filtering, Web-basic-Auth,  Web-IP-Security
    state: present
  listen: install features

- name: Web App tools
  win_feature:
    name: Web-App-Dev, Web-AppInit, Web-Net-Ext, Web-Asp-Net, Web-Net-Ext45, Web-ASP, Web-Asp-Net45, Web-CGI, Web-ISAPI-Ext, Web-ISAPI-Filter, Web-Includes, Web-WebSockets
    state: present
  listen: install features

- name: Install Web management Tools
  win_feature:
    name: Web-Mgmt-Tools, Web-Mgmt-Console,Web-WMI, Web-Scripting-Tools, Web-Metabase
    state: present
  listen: install features

# Force - remove features

- name: Install Web management Tools - Remove
  win_feature:
    name: Web-Mgmt-Compat, Web-Lgcy-Mgmt-Console
    state: absent
  listen: remove features

- name: Install IIS (Core Web-Server & tools) - Remove
  win_feature:
    name: Web-Dir-Browsing, Web-DAV-Publishing
    state: absent
  listen: remove features

- name: Web security tools - Remove
  win_feature:
    name: Web-Client-Auth, Web-Digest-Auth, Web-Cert-Auth, Web-Url-Auth, Web-Windows-Auth
    state: absent
  listen: remove features

- name: Web performance tools - Remove
  win_feature:
    name: Web-Dyn-Compression
    state: absent
  listen: remove features

# remove defaults

- name: Remove Defaults - Default Web Site
  win_iis_website:
    name: "Default Web Site"
    state: absent
  listen: remove defaults

- name: Remove Defaults - DefaultAppPool
  win_iis_webapppool:
    name: "DefaultAppPool"
    state: absent
  listen: remove defaults

- name: Remove Defaults - .NET v2.0
  win_iis_webapppool:
    name: ".NET v2.0"
    state: absent
  listen: remove defaults

- name: Remove Defaults - .NET v2.0 Classic
  win_iis_webapppool:
    name: ".NET v2.0 Classic"
    state: absent
  listen: remove defaults

- name: Remove Defaults - .NET v4.5
  win_iis_webapppool:
    name: ".NET v4.5"
    state: absent
  listen: remove defaults

- name: Remove Defaults - .NET v4.5 Classic
  win_iis_webapppool:
    name: ".NET v4.5 Classic"
    state: absent
  listen: remove defaults

- name: Remove Defaults - Classic .NET AppPool
  win_iis_webapppool:
    name: "Classic .NET AppPool"
    state: absent
  listen: remove defaults

