---

- name: restart iis
  win_service:
    name: w3svc
    state: restarted

# Force - remove features

- name: Install Web management Tools - Remove
  win_feature:
    name: Web-Mgmt-Compat, Web-Lgcy-Mgmt-Console
    state: absent
  listen: remove features

- name: Install IIS (Core Web-Server & tools) - Remove
  win_feature:
    name: Web-Dir-Browsing, Web-DAV-Publishing
    state: absent
  listen: remove features

- name: Web security tools - Remove
  win_feature:
    name: Web-Client-Auth, Web-Digest-Auth, Web-Cert-Auth, Web-Url-Auth, Web-Windows-Auth
    state: absent
  listen: remove features

- name: Web performance tools - Remove
  win_feature:
    name: Web-Dyn-Compression
    state: absent
  listen: remove features

# remove defaults

- name: Remove Defaults - Default Web Site
  win_iis_website:
    name: "Default Web Site"
    state: absent
  listen: remove defaults

- name: Remove Defaults - DefaultAppPool
  win_iis_webapppool:
    name: "DefaultAppPool"
    state: absent
  listen: remove defaults

- name: Remove Defaults - .NET v2.0
  win_iis_webapppool:
    name: ".NET v2.0"
    state: absent
  listen: remove defaults

- name: Remove Defaults - .NET v2.0 Classic
  win_iis_webapppool:
    name: ".NET v2.0 Classic"
    state: absent
  listen: remove defaults

- name: Remove Defaults - .NET v4.5
  win_iis_webapppool:
    name: ".NET v4.5"
    state: absent
  listen: remove defaults

- name: Remove Defaults - .NET v4.5 Classic
  win_iis_webapppool:
    name: ".NET v4.5 Classic"
    state: absent
  listen: remove defaults

- name: Remove Defaults - Classic .NET AppPool
  win_iis_webapppool:
    name: "Classic .NET AppPool"
    state: absent
  listen: remove defaults

