---
# tasks file for harden_networksecurity

- name: "Win CIS | Section 2.3.11.1 | Ensure 'Network security: Allow Local System to use computer identity for NTLM' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    name: "UseMachineId"
    data: "1"
    type: dword

- name: "Win CIS | Section 2.3.11.2 | Ensure 'Network security: Allow LocalSystem NULL session fallback' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    name: "RestrictAnonymous"
    data: "1"
    type: dword

- name: "Win CIS | Section 2.3.11.3 | Ensure 'Network Security: Allow PKU2U authentication requests to this computer to use online identities' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\pku2u
    name: "AllowOnlineID"
    data: "1"
    type: dword

- name: "Win CIS | Section 2.3.11.4 | Ensure 'Network security: Configure encryption types allowed for Kerberos' is set to 'AES128_HMAC_SHA1, AES256_HMAC_SHA1, Future encryption types'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Kerberos\Parameters
    name: "SupportedEncryptionTypes"
    data: "2147483640"
    type: dword

- name: "Win CIS | Section 2.3.11.5 | Ensure 'Network security: Do not store LAN Manager hash value on next password change' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    name: "NoLMHash"
    data: "1"
    type: dword

- name: "Win CIS | Section 2.3.11.6 | Ensure 'Network security: Force logoff when logon hours expire' is set to 'Enabled'"
  win_security_policy:
    section: System Access
    key: ForceLogoffWhenHourExpire 
    value: "1"

- name: "Win CIS | Section 2.3.11.7 | Ensure 'Network security: LAN Manager authentication level' is set to 'Send NTLMv2 response only. Refuse LM & NTLM'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    name: "LmCompatibilityLevel"
    data: "5"
    type: dword

- name: "Win CIS | Section 2.3.11.8 | Ensure 'Network security: LDAP client signing requirements' is set to 'Negotiate signing' or higher"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\LDAP
    name: "LDAPClientIntegrity"
    data: "1"
    type: dword

- name: "Win CIS | Section 2.3.11.9 | Ensure 'Network security: Minimum session security for NTLM SSP based (including secure RPC) clients' is set to 'Require NTLMv2 session security, Require 128-bit encryption'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0
    name: "NTLMMinClientSec"
    data: "537395200"
    type: dword

- name: "Win CIS | Section 2.3.11.10 | Ensure 'Network security: Minimum session security for NTLM SSP based (including secure RPC) servers' is set to 'Require NTLMv2 session security, Require 128-bit encryption'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0
    name: "NTLMMinServerSec"
    data: "537395200"
    type: dword
