---
# This playbook installs the .net core framework 4.5

- name: install .net core framework 4.5 role
  hosts: '{{ host }}'
  tasks:
  
    - name: install core Web components
      win_feature:
        name: NET-Framework-45-Features
        state: present
        include_sub_features: True
        include_management_tools: true
      register: win_feature

    - name: reboot if new features requires a windows reboot
      win_reboot:
      when: win_feature.reboot_required
