- name: add gpg key
  apt_key:
    url: "{{ docker_repo_key }} "
    state: present

- name: Add repository
  apt_repository:
    repo: "{{ docker_repo }}"

- name: install docker and dependencies
  apt:
    name: "{{ docker_packages }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ docker_packages}}"

- name: Install docker-compose
  ansible.builtin.shell: |
    curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
    ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
    docker-compose --version 

- name: install the package, force upgrade
  pip:
    name: pip
    executable: pip3
    state: latest

- name: upgrade python-docker
  pip:
    name: docker
    state: latest

- name: Add user to docker group
  user:
    name: vagrant
    group: docker

- name: start docker
  service:
    name: docker
    state: started
    enabled: yes


